# Generated by Django 5.1.4 on 2025-01-15 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealProcesses',
            fields=[
                ('id_process', models.AutoField(primary_key=True, serialize=False)),
                ('date_time_setting_status', models.DateTimeField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'appeal_processes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Appeals',
            fields=[
                ('id_appeals', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('description_problem', models.TextField()),
                ('photo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appeals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('name_official', models.CharField(max_length=255)),
                ('name_short', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id_city', models.AutoField(primary_key=True, serialize=False)),
                ('name_city', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Citizens',
            fields=[
                ('id_citizen', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True)),
                ('tel', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('house', models.CharField(blank=True, max_length=255, null=True)),
                ('flat', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'citizens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CityServices',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('house', models.CharField(blank=True, max_length=100, null=True)),
                ('flat', models.IntegerField(blank=True, null=True)),
                ('tel', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'city_services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id_sotrudnik', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id_message', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('date_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('name_status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'statuses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Streets',
            fields=[
                ('id_street', models.AutoField(primary_key=True, serialize=False)),
                ('name_street', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'streets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
