# Generated by Django 5.1.4 on 2025-01-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeals',
            fields=[
                ('id_appeals', models.IntegerField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('description_problem', models.TextField(blank=True, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appeals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id_category', models.IntegerField(primary_key=True, serialize=False)),
                ('name_official', models.CharField(blank=True, max_length=255, null=True)),
                ('name_short', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id_city', models.IntegerField(primary_key=True, serialize=False)),
                ('name_city', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Citizens',
            fields=[
                ('id_citizen', models.IntegerField(primary_key=True, serialize=False)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True)),
                ('tel', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('house', models.CharField(blank=True, max_length=255, null=True)),
                ('flat', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'citizens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id_sotrudnik', models.IntegerField(primary_key=True, serialize=False)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id_message', models.IntegerField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Processing',
            fields=[
                ('id_process', models.IntegerField(primary_key=True, serialize=False)),
                ('date_time_setting_status', models.DateTimeField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'processing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id_service', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('house', models.CharField(blank=True, max_length=100, null=True)),
                ('flat', models.IntegerField(blank=True, null=True)),
                ('tel', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id_status', models.IntegerField(primary_key=True, serialize=False)),
                ('name_status', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'statuses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Streets',
            fields=[
                ('id_street', models.IntegerField(primary_key=True, serialize=False)),
                ('name_street', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'streets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
